### ISSUE TITLE
Unable to load Basic UI and Classic UI in ESH

### ISSUE THREAD

**Issue by amarpulli544** [maggu2810/smarthome-packaging-sample-karaf#3]
Hello, @maggu2810 
Unable to load basic ui and calssic ui in esh through Karaf . I have tried through localhost:8181/classicui/app?sitemap=sitemapname , it will not work for me. Is there would be any configurations to access classic ui and basic ui.
Thanks,
Amar.

**Comment by maggu2810** [comment]
Hi @amarpulli544,
can you please close your issues, the next time?
* https://github.com/maggu2810/shk/issues/8
* https://github.com/maggu2810/smarthome-packaging-sample-karaf/issues/1

I gave it a try myself, installed the respective features `esh-ui-basic` and `esh-ui-classic` and both UIs are working.

So, I don't think there is an issue here.
Is it correct that you don't know what to do?

You should read about how to use Karaf at all because this is the environment that is used by this project.

Have you seen: https://github.com/maggu2810/smarthome-packaging-sample-karaf/issues/2#issuecomment-277456078

**Comment by maggu2810** [comment]
After doing a
```text
feature:install esh-ui-basic esh-ui-classic
```

You should start reading about the feature concept of Karaf and how to install new feature and bundles. 😉

**Comment by amarpulli544** [comment]
@maggu2810 
Thanks for spend your valuable time for me. I got the basic ui in bundle list. But how i can access basic ui from server. Accessing basic ui like http://loacalhost:8181/basicui/  .Here is my bundle list

```
165 | Active |  80 | 0.9.0.201702031201    | Eclipse SmartHome UI
166 | Active |  80 | 0.9.0.201702031201    | Eclipse SmartHome UI Icons
167 | Active |  80 | 0.9.0.201702031201    | Eclipse SmartHome Classic IconSet
168 | Active |  80 | 0.9.0.201702031201    | Eclipse SmartHome Paper UI
169 | Active |  80 | 2.9.2                 | Xtend Runtime Library
170 | Active |  80 | 2.9.2                 | Xtend Macro Interfaces
171 | Active |  80 | 2.9.2                 | Xtext
172 | Active |  80 | 2.9.2                 | Xtext Common Types
173 | Active |  80 | 2.9.2                 | JSR-45 Smap installer
174 | Active |  80 | 2.9.2                 | Xtext Utility
175 | Active |  80 | 2.9.2.v20160428-1452  | Xbase Model
176 | Active |  80 | 2.9.2                 | Xbase Runtime Library
192 | Active |  80 | 2.2.0                 | JUPnP Library
193 | Active |  80 | 1.9.6                 | MIME streaming extension
194 | Active |  80 | 1.0.9                 | mapdb
195 | Active |  80 | 5.0.2                 | Require-Bundle Fix :: org.objectweb
.asm
201 | Active |  80 | 3.2.0                 | Commons Net
202 | Active |  80 | 0.9.0.201702031201    | Eclipse SmartHome Basic UI
203 | Active |  80 | 0.9.0.201702031201    | Eclipse SmartHome WebApp UI
karaf@root()>
```
I am doing as of you said, but didn't get classic ui in bundle list.
Thanks,
Amar.

**Comment by maggu2810** [comment]
#4
