### ISSUE TITLE
Loading Basic UI  is Done

### ISSUE THREAD

**Issue by amarpulli544** [maggu2810/smarthome-packaging-sample-karaf#4]
@maggu2810 
Thanks for spending your valuable time for me. I got the basic ui in bundle list. But how i can access basic ui and classic ui from server. Accessing basic ui like http://loacalhost:8181/basicui/ .Here is my bundle list

```
165 | Active |  80 | 0.9.0.201702031201    | Eclipse SmartHome UI
166 | Active |  80 | 0.9.0.201702031201    | Eclipse SmartHome UI Icons
167 | Active |  80 | 0.9.0.201702031201    | Eclipse SmartHome Classic IconSet
168 | Active |  80 | 0.9.0.201702031201    | Eclipse SmartHome Paper UI
169 | Active |  80 | 2.9.2                 | Xtend Runtime Library
170 | Active |  80 | 2.9.2                 | Xtend Macro Interfaces
171 | Active |  80 | 2.9.2                 | Xtext
172 | Active |  80 | 2.9.2                 | Xtext Common Types
173 | Active |  80 | 2.9.2                 | JSR-45 Smap installer
174 | Active |  80 | 2.9.2                 | Xtext Utility
175 | Active |  80 | 2.9.2.v20160428-1452  | Xbase Model
176 | Active |  80 | 2.9.2                 | Xbase Runtime Library
192 | Active |  80 | 2.2.0                 | JUPnP Library
193 | Active |  80 | 1.9.6                 | MIME streaming extension
194 | Active |  80 | 1.0.9                 | mapdb
195 | Active |  80 | 5.0.2                 | Require-Bundle Fix :: org.objectweb
.asm
201 | Active |  80 | 3.2.0                 | Commons Net
202 | Active |  80 | 0.9.0.201702031201    | Eclipse SmartHome Basic UI
203 | Active |  80 | 0.9.0.201702031201    | Eclipse SmartHome WebApp UI
karaf@root()>
```
I am doing as of you said, but didn't get classic ui in bundle list.
Thanks,
Amar.

**Comment by maggu2810** [comment]
Please be fair...
I already tried to clarify but again:
This project is an example how to package `Eclipse SmartHome``for `Karaf` -- how to create a custom Karaf distribution that could be used for Eclipse SmartHome.
This could be used by developers to create their own product.
It is just about packaging.
It is not about any support for the usage of `Karaf` or `Eclipse SmartHome`.
So, if you cannot access the Eclipse SmartHome UIs in your browser, I don't see any relationship to the packaging or at least a bug in the packaging.

It is not about I don't care about problems of others, but this is not the correct place.
It is also technically wrong, because there is no issue in the example of how to package.

If you would like a "product" to use, with a community for support and a lot of documentation, then you should have a look at `openHAB`.

And a last time to give you support for your problem -- I hope you understand that I don't like to be harsh, but I don't have the time to provide support about the usage of the Karaf and ESH combination:

```karaf@root()> http:list
ID  | Servlet                | Servlet-Name    | State       | Alias               | Url
------------------------------------------------------------------------------------------------------------
77  | ResourceServlet        | /res            | Deployed    | /system/console/res | [/system/console/res/*]
165 | ProxyServlet           | ServletModel-11 | Deployed    | /proxy              | [/proxy/*]
203 | WebAppServlet          | ServletModel-22 | Deployed    | /classicui/app      | [/classicui/app/*]
165 | ChartServlet           | ServletModel-12 | Deployed    | /chart              | [/chart/*]
133 | AudioServlet           | ServletModel-9  | Undeployed  | /audio              | [/audio/*]
203 | CmdServlet             | ServletModel-24 | Deployed    | /classicui/CMD      | [/classicui/CMD/*]
166 | IconServlet            | ServletModel-14 | Deployed    | /icon               | [/icon/*]
202 | CmdServlet             | ServletModel-18 | Deployed    | /basicui/CMD        | [/basicui/CMD/*]
202 | WebAppServlet          | ServletModel-19 | Deployed    | /basicui/app        | [/basicui/app/*]
77  | KarafOsgiManager       | ServletModel-2  | Deployed    | /system/console     | [/system/console/*]
10  | ServletContainerBridge | ServletModel-7  | Deployed    | /rest               | [/rest/*]
203 | ResourceServlet        | web             | Deployed    | /classicui          | [/classicui/*]
192 | AsyncServlet           | ServletModel-5  | Deployed    | /upnpcallback       | [/upnpcallback/*]
```

For me `http://localhost:8181/classicui/app` is working (it only complains about the missing sitemap, because I have not created a demo one).
For me `http://localhost:8181/basicui/app` is working, too.

**Comment by amarpulli544** [comment]
@maggu2810 
Sorry for closing the issues, because i am new to development world. So, I would like to know learning and develop new things through ESH, right now i am working on User Interfaces. I have to developed and deployed  making my self User Interface. What are the basic things required for developing User Interface.
Thanks,
Amar.

**Comment by maggu2810** [comment]
You have the choose about the tooling you use for development. There are different ways to do it.
For development you could use e.g. the Eclipse IDE setup of the Eclipse SmartHome project.

If you don't want to use p2, Tycho, Manifest first approach etc. you can also use the shk Eclipse IDE setup.
It is the one that I use for development of stuff that is using the Eclipse SmartHome project but that is not part of the official Eclipse SmartHome project.

If you want to make some contribution to the Eclipse SmartHome project perhaps you should use the official IDE.

For the runtime it does not matter how you have created the OSGi bundle.
